### ISSUE TITLE
能否支持Android 10 以上uri地址存储

### ISSUE THREAD

**Issue by 3-BodyCoding** [ssseasonnn/DownloadX#17]
能否支持Android 10 以上uri地址存储

**Comment by 3-BodyCoding** [comment]
发现一个问题，contentLength = -1时下载失败,有的服务器没有contentLength标识，DownloadX会下载失败。我用okhttp是可以下载的，只是无法获取进度。

**Comment by ssseasonnn** [comment]
下载地址有吗？发一下看看

**Comment by 3-BodyCoding** [comment]
比如这个：https://pipedproxy-bom.kavin.rocks/videoplayback?expire=1685524301&ei=7bp2ZOSpD9P2juMP4Z2LgA4&ip=140.238.245.97&id=o-ABOWDiP3T8727NYkk9WB-kgRGmfrJL2awwfKXZJlshjG&itag=137&source=youtube&requiressl=yes&mh=FL&mm=31%2C26&mn=sn-cvh7knzs%2Csn-h557sn6l&ms=au%2Conr&mv=m&mvi=2&pl=21&initcwndbps=23707500&spc=qEK7Bx8IgyQAbziOBB3ewavtlCNEt_M&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=230849236&dur=796.729&lmt=1683039938078450&mt=1685502286&fvip=5&keepalive=yes&fexp=24007246%2C24363391&beids=24350018&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANiqykRFm4OQvpjwxcxnl2FloKovT3bbUCgEqMlEW3DpAiEAs7Obj1rMqwdBhvjRcS9OOHWY2hYFTb8GTg_sTkye87I%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgRkXnVd6BURjnnjIlVZLOOHQMbJDEKsI11XXqVs1uWcECIQDN_uPLouZShEi9AauDel6BkEoBLwzw1Kaqr5MD-tMhEw%3D%3D&cpn=1O572wZ0uoBA7spZ&host=rr2---sn-cvh7knzs.googlevideo.com

**Comment by ssseasonnn** [comment]
链接打不开
