### ISSUE TITLE
使用GlobalScope下载时退出当前Activity下载无法继续

### ISSUE THREAD

**Issue by Travellingpoet** [ssseasonnn/DownloadX#18]
如题，还有个问题在下载页Acitvity退出后如何监听下载状态和进度，监听state如果传入GlobalScope会报错

**Comment by ssseasonnn** [comment]
报什么错？问问题的时候能不能描述清楚一点呀？起码你得把报错信息贴出来吧

**Comment by Travellingpoet** [comment]
我看你的demo里监听状态都是传的lifecycleowner 所以我想问一下退出当前Activity或者Fragment后能否继续监听下载状态
 val item = adapter.getItem(position)
                val downloadTask = GlobalScope.download(
                    checkHttpUrl(item.url),
                    item.name,
                    "$DEFAULT_SAVE_PATH/map"
                )
 downloadTask.start()
我使用GlobalScope线程开启下载任务时，退出了当前fragment之后下载任务就停止了

**Comment by ssseasonnn** [comment]
你用GlobalScope去下载，页面销毁仍然会继续下载，但是进度监听肯定是跟你页面生命周期绑定的，不然页面销毁了还继续监听下载进度更新UI，不就内存泄露了吗？

**Comment by ssseasonnn** [comment]
所以你的目的是什么？你能描述一下你的业务场景吗？

**Comment by Travellingpoet** [comment]
不是 我是说页面销毁后下载任务就停止了

**Comment by ssseasonnn** [comment]
不会的，使用GlobalScope，页面销毁下载不会停止

**Comment by ssseasonnn** [comment]
demo中有一个TestActivity，你可以打开它验证一下，点击开始下载后退出TestActivity，等待一段时间后你可以看到下载目录中的下载文件

**Comment by Travellingpoet** [comment]
之前确实是我代码的问题导致页面销毁停止，但是我还有个问题为什么你的demo源码中onAttach绑定的downloadTask的对象与button点击事件的downloadTask对象是同一个？ 点击button的时候按照你的代码不是应该会new一个全新的对象吗
 onAttach {
                    val downloadTask = GlobalScope.download(data.apkUrl)

                    data.progressJob?.cancel()
                    data.progressJob = downloadTask.state()
                        .onEach {
                            itemBinding.button.setState(it)
                            Log.e("========downloadTask","$downloadTask")
                            Log.e("========data","$data")
                        }
                        .launchIn(lifecycleScope)
                }


itemBinding.button.setOnClickListener {
                        val downloadTask = GlobalScope.download(data.apkUrl)
                        Log.e("========downloadStart","$downloadTask")
                        when {
                            downloadTask.isSucceed() -> {
                                installApk(downloadTask.file()!!)
                            }
                            downloadTask.isStarted() -> {
                                downloadTask.stop()
                            }
                            else -> {
                                downloadTask.start()
                                Log.e("========data","$data")
                            }
                        }
                    }

**Comment by ssseasonnn** [comment]
会根据url来判断是不是同一个下载任务，如果url相同，则不会创建新的task

**Comment by Travellingpoet** [comment]
我打开日志看了一下 url是相同的但是每次点击都创建了新的下载任务
2023-07-13 16:13:54.104 14238-14238 jerry                   com.north.arrow.technology           D  ========url:http://10.252.176.145:8080/filestore/file/dp/8552?extension=mspk&redirect=download
2023-07-13 16:13:54.104 14238-14238 jerry                   com.north.arrow.technology           D  ========downLoadTask:com.north.arrow.module.common.download.core.DownloadTask@f66ba0e
2023-07-13 16:14:02.692 14238-14238 jerry                   com.north.arrow.technology           D  ========url:http://10.252.176.145:8080/filestore/file/dp/8552?extension=mspk&redirect=download
2023-07-13 16:14:02.693 14238-14238 jerry                   com.north.arrow.technology           D  ========downLoadTask:com.north.arrow.module.common.download.core.DownloadTask@c503849
2023-07-13 16:14:08.084 14238-14238 jerry                   com.north.arrow.technology           D  ========url:http://10.252.176.145:8080/filestore/file/dp/8552?extension=mspk&redirect=download
2023-07-13 16:14:08.084 14238-14238 jerry                   com.north.arrow.technology           D  ========downLoadTask:com.north.arrow.module.common.download.core.DownloadTask@b2b7cb9

**Comment by ssseasonnn** [comment]
你代码怎么写的？贴出来看看

**Comment by Travellingpoet** [comment]
offlineMapAdapter.setOnItemChildClickListener { adapter, view, position ->
            if (view.id == R.id.iv_download) {
                val item = adapter.getItem(position) as Item
                val downloadTask = GlobalScope.download(
                    checkHttpUrl(item.url),
                    item.name,
                    "$DEFAULT_SAVE_PATH/map"
                )
                L.d("========url:${checkHttpUrl(item.url)}")
                L.d("========downLoadTask:$downloadTask")
                when {
                    downloadTask.isSucceed() -> {
                      
                    }

                    downloadTask.isStarted() -> {
                        downloadTask.stop()
                    }
                    else -> {
                        downLoadService()
                        downloadTask.start()
                    }
                }
            }
        }

**Comment by ssseasonnn** [comment]
你断点调试一下呢，没看出有啥问题 😂

**Comment by Travellingpoet** [comment]
private val taskMap = ConcurrentHashMap<String, DownloadTask>()我每次点击的时候这个map的size都是0

**Comment by Travellingpoet** [comment]
按理说我第一次初始化的时候就创建了所有的downloadTask 但是每次调用这个downloadConfig.taskManager.add(task)方法时 这个map的size都是空的

**Comment by Travellingpoet** [comment]
offlineMapAdapter.data.forEach { item->
                val downloadTask = GlobalScope.download(
                    checkHttpUrl(item.url),
                    item.name,
                    "$DEFAULT_SAVE_PATH/map"
                )
                L.d("========downloadTask: $downloadTask")
                setDownloadProcessListener(item, downloadTask, offlineMapAdapter)
            }
我这样初始化不行吗？ 因为你是在onAttcah里面初始化的 我就直接把adpater数据轮询了

**Comment by Travellingpoet** [comment]
找到问题了😂 DefaultTaskManager这个manager应该是是静态的object  我看你代码里写的是class
