### ISSUE TITLE
下载成功后仍回调多次

### ISSUE THREAD

**Issue by flyfishxu** [ssseasonnn/DownloadX#6]
`            // 创建任务
            val downloadTask = lifecycleScope.download(downloadURL, "base.apk", this.filesDir.toString())
            downloadTask.state()
                    .onEach { state ->
                        Log.i("Download APK", "Downloaded Progress: ${state.progress.percent()}")
                        loadingDialog.progress = state.progress.percent().toInt()
                        if (state is State.Succeed) {
                            loadingDialog.dismiss()
                            loadingDialog.progress = 0
                            Toast.makeText(this, "Download done!", Toast.LENGTH_LONG).show()
                            installApk(this, ProgressDialog(this), "this.filesDir.toString()/base.apk")
                        }
                    }
                    .launchIn(lifecycleScope) // 使用lifecycleScope
            downloadTask.start()`
当本地已存在文件时下载会回调多次

**Comment by ssseasonnn** [comment]
谢谢反馈，我会尽快修复，你可以暂时先使用标记变量控制一下

**Comment by cay8888** [comment]
修复了？
